on:
  push:
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
    uses: threatrix/threat-agent-scan/.github/workflows/scan-repo-reusable.yaml@master
    with:  
      eid: ${{ vars.EID }}
      oid: ${{ vars.ORGID }}
    secrets: 
      TOKEN: ${{ secrets.TOKEN }}
      THREATRIX_SERVER_API_KEY: ${{ secrets.THREATRIX_SERVER_API_KEY }}
