on:
  push:
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
    uses: rmashchenko/threat-agent-scan/blob/main/.github/workflows/scan-repo-reusable.yaml@main
    with:  
      eid: ${{ vars.EID }}
      oid: ${{ vars.ORGID }}
    secrets: inherit
