on:
  push:
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
    uses: threatrix/threat-agent-scan/.github/workflows/scan-repo-reusable.yaml@oid_and_eid_from_secrets
    with:
      eid: 3357b0a7-6a40-410f-af2e-ebc7823e7a5b
      oid: 89629e27-bd46-4106-b162-a94da1ee91e5
    secrets: 
      TOKEN: ${{ secrets.TOKEN }}
      THREATRIX_SERVER_API_KEY: ${{ secrets.THREATRIX_SERVER_API_KEY }}
