on:
  push:
   branches:
    - 'main'
    - 'master'
  pull_request:
    types:
      - 'opened'
      - 'reopened'
jobs:
  execute-scan-workflow:
    uses: threatrix/threat-agent-scan/.github/workflows/scan-repo-reusable.yaml@master
    with:
      eid: f512a2c4-b898-4166-bf9e-d5f6c097e49d
      oid: b9320501-45f8-4d61-833f-b15f4e143b49
      app-name: threat-matrix-2-actions
      trx-host: http://localhost:4200
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      THREATRIX_SERVER_API_KEY: ${{ secrets.TRX_API_KEY }}